[project]
<<<<<<< HEAD
name = "kggl_support"
authors = [
    { name = "KG GL", email = "krishnapriya.p@kggl.com"}
]
description = "KG GL Support Service"
=======
name = "erpnext"
authors = [
    { name = "Frappe Technologies Pvt Ltd", email = "developers@frappe.io"}
]
description = "Open Source ERP"
>>>>>>> 005df08 (chore(release): Bumped to Version 15.47.3)
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
<<<<<<< HEAD
    # "frappe~=15.0.0" # Installed and managed by bench.
=======
    # Core dependencies
    "pycountry~=22.3.5",
    "Unidecode~=1.3.6",
    "barcodenumber~=0.5.0",
    "rapidfuzz~=2.15.0",
    "holidays~=0.28",

    # integration dependencies
    "googlemaps",
    "plaid-python~=7.2.1",
    "python-youtube~=0.8.0",

    # Not used directly - required by PyQRCode for PNG generation
    "pypng~=0.20220715.0",
>>>>>>> 005df08 (chore(release): Bumped to Version 15.47.3)
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

<<<<<<< HEAD
# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
=======
[tool.bench.frappe-dependencies]
frappe = ">=15.40.4,<16.0.0"

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
    "RUF",
]
ignore = [
    "B017", # assertRaises(Exception) - should be more specific
    "B018", # useless expression, not assigned to anything
    "B023", # function doesn't bind loop variable - will have last iteration's value
    "B904", # raise inside except without from
    "E101", # indentation contains mixed spaces and tabs
    "E402", # module level import not at top of file
    "E501", # line too long
    "E741", # ambiguous variable name
    "F401", # "unused" imports
    "F403", # can't detect undefined names from * import
    "F405", # can't detect undefined names from * import
    "F722", # syntax error in forward type annotation
    "W191", # indentation contains tabs
    "RUF001", # string contains ambiguous unicode character
]
typing-modules = ["frappe.types.DF"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true


[project.urls]
Homepage = "https://erpnext.com/"
Repository = "https://github.com/frappe/erpnext.git"
"Bug Reports" = "https://github.com/frappe/erpnext/issues"
>>>>>>> 005df08 (chore(release): Bumped to Version 15.47.3)
